# Generated by Django 4.2.29 on 2026-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_api_key',
            field=models.CharField(blank=True, help_text='Email service API key (SendGrid, Mailgun, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_service',
            field=models.CharField(choices=[('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('smtp', 'SMTP')], default='sendgrid', help_text='Email service provider', max_length=50),
        ),
    ]
