# Generated by Django 4.2.29 on 2026-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_api_key_user_email_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Киргизский сом (KGS)'), ('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)'), ('RUB', 'Российский рубль (RUB)')], default='KGS', help_text='Валюта для отображения цен', max_length=3),
        ),
    ]
