export { useDashboardStats, useExpiringItems, useActivityFeed, useCostByMonth, useFuelStatsByMonth, useRecentFuelEntries, useVehicleConsumption } from './hooks/useDashboard'
export { StatCard, StatsGrid } from './ui/StatCard'
export { TrendIndicator } from './ui/TrendIndicator'
export { ExpiringSoon } from './ui/ExpiringSoon'
export { RecentActivity } from './ui/RecentActivity'
export { FuelChart } from './ui/FuelChart'
export { CarsByStatus } from './ui/CarsByStatus'
export { CostBreakdownChart } from './ui/CostBreakdownChart'
export { ActivityFeed } from './ui/ActivityFeed'
export { CustomizationPanel, loadDashboardPreferences, saveDashboardPreferences } from './ui/CustomizationPanel'
export { VehicleConsumptionList } from './ui/VehicleConsumptionList'
