# Generated by Django 4.2.29 on 2026-03-07 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('fuel_consumption', 'Fuel Consumption'), ('maintenance_costs', 'Maintenance Costs'), ('insurance_inspection', 'Insurance & Inspection'), ('vehicle_utilization', 'Vehicle Utilization'), ('cost_analysis', 'Cost Analysis'), ('custom', 'Custom Report')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('car_ids', models.JSONField(blank=True, help_text='List of car IDs or null for all', null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Additional filters')),
                ('summary', models.JSONField(default=dict, help_text='Report summary data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='reports_sav_company_8b7bb5_idx'), models.Index(fields=['company', 'report_type'], name='reports_sav_company_b98d65_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(max_length=50)),
                ('default_from_date', models.CharField(default='first_day_of_month', help_text='first_day_of_month, first_day_of_year, custom', max_length=20)),
                ('default_to_date', models.CharField(default='last_day_of_month', help_text='last_day_of_month, today, custom', max_length=20)),
                ('default_car_ids', models.JSONField(blank=True, null=True)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('show_charts', models.BooleanField(default=True)),
                ('chart_types', models.JSONField(default=list, help_text='Preferred chart types: ["bar", "line", "pie"]')),
                ('show_totals', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Available to all users in company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'report_type'], name='reports_rep_company_f9a879_idx')],
            },
        ),
    ]
