# Generated by Django 4.2.29 on 2026-03-10 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('record_count', models.IntegerField(default=0, help_text='Number of records exported')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filters applied to the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='companies.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='reports_exp_company_b9c5c3_idx'), models.Index(fields=['user', '-created_at'], name='reports_exp_user_id_74fcc2_idx'), models.Index(fields=['report_type'], name='reports_exp_report__333da3_idx')],
            },
        ),
    ]
