# Generated by Django 4.2.29 on 2026-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_exportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('fuel_consumption', 'Fuel Consumption'), ('maintenance_costs', 'Maintenance Costs'), ('insurance_inspection', 'Insurance & Inspection'), ('vehicle_utilization', 'Vehicle Utilization'), ('cost_analysis', 'Cost Analysis'), ('cost_per_km', 'Cost per Km'), ('custom', 'Custom Report')], max_length=50),
        ),
    ]
