# Generated by Django 4.2.27 on 2025-12-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('numplate', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('fueltype', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('driver', models.CharField(blank=True, default='-', max_length=150)),
                ('drivers_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_card', models.CharField(blank=True, default='-', max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('commissioned_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'numplate'], name='fleet_car_company_f6eb64_idx'), models.Index(fields=['company', 'brand'], name='fleet_car_company_c09405_idx'), models.Index(fields=['company', 'status'], name='fleet_car_company_c9d58c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('company', 'numplate'), name='uq_car_company_numplate'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('vin__isnull', False), models.Q(('vin', ''), _negated=True)), fields=('company', 'vin'), name='uq_car_company_vin'),
        ),
    ]
