# Generated by Django 4.2.27 on 2025-12-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_carphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('part_price', models.PositiveIntegerField(default=0)),
                ('job_description', models.CharField(blank=True, max_length=255)),
                ('job_price', models.PositiveIntegerField(default=0)),
                ('installed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='fleet.car')),
            ],
            options={
                'ordering': ['-installed_at', '-id'],
                'indexes': [models.Index(fields=['car', 'installed_at'], name='fleet_spare_car_id_42c495_idx')],
            },
        ),
    ]
