# Generated by Django 4.2.27 on 2025-12-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_spare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tire_photos/')),
                ('installed_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='fleet.car')),
            ],
            options={
                'ordering': ['-installed_at', '-id'],
                'indexes': [models.Index(fields=['car', 'installed_at'], name='fleet_tires_car_id_cad976_idx')],
            },
        ),
    ]
