# Generated by Django 4.2.27 on 2026-01-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_accumulator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('liters', models.PositiveIntegerField(default=0)),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('monthly_mileage', models.PositiveIntegerField(default=0)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('month_name', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='fleet.car')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fuel',
            constraint=models.UniqueConstraint(fields=('car', 'year', 'month'), name='uq_fuel_car_year_month'),
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['car', 'year', 'month'], name='fleet_fuel_car_yy_mm_idx'),
        ),
    ]
