# Generated by Django 4.2.27 on 2026-01-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(default='OSAGO', max_length=50)),
                ('number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='fleet.car')),
            ],
            options={
                'ordering': ['-end_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['car', 'end_date'], name='fleet_ins_car_end_idx'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('inspected_at', models.DateField()),
                ('cost', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet.car')),
            ],
            options={
                'ordering': ['-inspected_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['car', 'inspected_at'], name='fleet_insp_car_date_idx'),
        ),
    ]
