# Generated by Django 4.2.29 on 2026-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_insurance_inspection'),
    ]

    operations = [
        # Cars indexes
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company', 'status'], name='fleet_car_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company', 'numplate'], name='fleet_car_company_numplate_idx'),
        ),
        
        # Fuel indexes
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['car', 'year', 'month'], name='fleet_fuel_car_year_month_idx'),
        ),
        
        # Insurance indexes
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['car', 'end_date'], name='fleet_insurance_car_enddate_idx'),
        ),
        
        # Inspection indexes
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['car', 'inspected_at'], name='fleet_inspection_car_inspectedat_idx'),
        ),
        
        # Spare parts indexes
        migrations.AddIndex(
            model_name='spare',
            index=models.Index(fields=['car', 'installed_at'], name='fleet_spare_car_installedat_idx'),
        ),
    ]
