# Generated by Django 4.2.27 on 2026-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20260402_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='region',
            field=models.CharField(blank=True, default='Кыргызстан', max_length=100),
        ),
    ]
