# Generated by Django 4.2.27 on 2026-05-31 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_car_region_optional'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fuel',
            name='uq_fuel_car_year_month',
        ),
        migrations.AddField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='fuel',
            name='odometer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['car', 'date'], name='fleet_fuel_car_id_002fc0_idx'),
        ),
    ]
