# Generated by Django 4.2.29 on 2026-06-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_fuel_add_date_odometer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='fleet_car_company_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='fleet_car_company_numplate_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuel',
            name='fleet_fuel_car_yy_mm_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuel',
            name='fleet_fuel_car_year_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='spare',
            name='fleet_spare_car_installedat_idx',
        ),
        # Inspection: remove duplicate old indexes, add one correct index
        migrations.RemoveIndex(
            model_name='inspection',
            name='fleet_insp_car_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='fleet_inspection_car_inspectedat_idx',
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['car', 'inspected_at'], name='fleet_inspe_car_id_19abe4_idx'),
        ),
        # Insurance: remove duplicate old indexes, add one correct index
        migrations.RemoveIndex(
            model_name='insurance',
            name='fleet_ins_car_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurance',
            name='fleet_insurance_car_enddate_idx',
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['car', 'end_date'], name='fleet_insur_car_id_7c8c26_idx'),
        ),
    ]
