# Generated by Django 4.2.29 on 2026-04-14 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', help_text='Auto-generated from first user message', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Сессия разговора (None для legacy сообщений)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='ai_aichatme_convers_c5b48c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['company', 'user', '-updated_at'], name='ai_aiconver_company_6eda32_idx'),
        ),
    ]
