# Generated by Django 4.2.26 on 2025-11-24 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название компании', max_length=255, verbose_name='Название компании')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор компании для URL', max_length=255, unique=True, verbose_name='Слаг')),
                ('country', models.CharField(default='Кыргызстан', help_text='Страна регистрации компании', max_length=100, verbose_name='Страна')),
                ('timezone', models.CharField(default='Asia/Bishkek', help_text='Часовой пояс компании', max_length=50, verbose_name='Часовой пояс')),
                ('default_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], default='ru', help_text='Язык интерфейса по умолчанию для компании', max_length=2, verbose_name='Язык по умолчанию')),
                ('default_currency', models.CharField(choices=[('KGS', 'Киргизский сом'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль')], default='KGS', help_text='Валюта для финансовых операций', max_length=3, verbose_name='Валюта по умолчанию')),
                ('legal_name', models.CharField(blank=True, help_text='Полное юридическое название компании', max_length=255, null=True, verbose_name='Юридическое название')),
                ('inn', models.CharField(blank=True, help_text='Идентификационный номер налогоплательщика', max_length=50, null=True, verbose_name='ИНН')),
                ('address', models.TextField(blank=True, help_text='Полный юридический адрес компании', null=True, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон компании', max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Контактный email компании', max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли компания в системе', verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, help_text='Администратор, создавший компанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['slug'], name='companies_c_slug_45751b_idx')],
            },
        ),
    ]
